# Makefile

<?if serial?>CC=gcc<?end if?><?if parallel?>CC=mpicc<?end if?>
CFLAGS=-c -std=c99 -Wall
LIBS=-lm
SOURCES=main.c memory.c xml.c messageboards.c partitioning.c <?if parallel?>propagate_messages.c propagate_agents.c<?end if?><?foreach functionfiles?> $filepath<?end foreach?>
DEPS=Makefile header.h low_primes.h

OBJECTS=$(SOURCES:.c=.o)
EXECUTABLE=main
RM=rm -f

all: $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS) 
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@ $(LIBS)

$(OBJECTS): $(DEPS)

.c.o:
	$(CC) $(CFLAGS) $< -o $@

clean:
	$(RM) *.o main.exe main
