# Makefile template file for FLAME
#
# FLAME is the FLAME source files
# SOURCE is the user source files
#
# The assumption is that the user only provides C files
# and a model files <file>.xml
#
DEFINES=-DNONE
<?if serial?>
CC=gcc
<?end if?>
<?if parallel?>
CC=mpicc
<?end if?>
CFLAGS=-c -std=c99 -Wall ${DEFINES}
LDFLAGS = 
LIBS=-lm

#FLAME source files
FLAME   = main.c memory.c xml.c messageboards.c partitioning.c <?if parallel?>propagate_messages.c propagate_agents.c <?end if?>
#FLAME auxilary files
AUX 	= dgraph.dot dgraph.svg

# FLAME generated model files
SOURCES = <?foreach functionfiles?> $filepath <?end foreach?>
HEADERS = header.h low_primes.h <?foreach xagent?> $name_agent_header.h <?end foreach?> 

DEPS=Makefile header.h low_primes.h

OBJECTS=$(SOURCES:.c=.o) $(FLAME:.c=.o)
EXECUTABLE=main
RM=rm -f

all: $(SOURCES) $(FLAME) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS) 
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@ $(LIBS)

$(OBJECTS): $(DEPS)

.c.o:
	$(CC) $(CFLAGS) $< -o $@

clean:
	$(RM) *.o $(EXECUTABLE) $(EXECUTABLE).exe
vclean:
	$(RM) main $(EXECUTABLE) $(EXECUTABLE).exe *.o  $(FLAME) $(HEADERS)  $(AUX) Makefile
